// src/styles/AccountStyle.js
import { StyleSheet } from "react-native";

export const COLORS = {
    BG: "#F6F8FC",
    TEXT: "#111",
    SUB: "#6B7280",
    BLUE: "#0B63F6",
    CARD: "#fff",
    BORDER: "#EEF2F8",
    RED: "#EF4444",
    MUTED: "#9AA0A6",
    WHITE: "#fff",
};

const styles = StyleSheet.create({
    safe: { flex: 1, backgroundColor: COLORS.BG },
    container: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: 18 },

    header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
    headerTitle: { fontSize: 22, fontWeight: "900", color: COLORS.TEXT },
    headerRight: { flexDirection: "row", gap: 10 },
    iconBtn: { width: 40, height: 40, borderRadius: 12, alignItems: "center", justifyContent: "center" },
    notifBadge: {
        position: "absolute",
        top: 6,
        right: 6,
        minWidth: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: COLORS.RED,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 4,
    },
    notifBadgeText: { color: COLORS.WHITE, fontSize: 10, fontWeight: "900" },

    profileCard: {
        backgroundColor: COLORS.BLUE,
        borderRadius: 16,
        padding: 14,
        borderWidth: 1,
        borderColor: "#1D4ED8",
    },
    profileTop: { flexDirection: "row", gap: 12, alignItems: "center" },
    avatar: {
        width: 66,
        height: 66,
        borderRadius: 33,
        backgroundColor: "#FACC15",
        alignItems: "center",
        justifyContent: "center",
    },
    avatarText: { fontSize: 26, fontWeight: "900", color: COLORS.TEXT },
    name: { fontSize: 18, fontWeight: "900", color: COLORS.WHITE },
    phone: { marginTop: 4, fontSize: 13, fontWeight: "700", color: "#EAF2FF" },

    editBtn: {
        marginTop: 10,
        alignSelf: "flex-start",
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "rgba(255,255,255,0.22)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.28)",
        borderRadius: 12,
        paddingHorizontal: 12,
        height: 34,
    },
    editBtnText: { color: COLORS.WHITE, fontWeight: "900", fontSize: 12.5 },

    vipPill: {
        marginTop: 12,
        alignSelf: "flex-start",
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "#FACC15",
        borderRadius: 14,
        paddingHorizontal: 12,
        height: 30,
    },
    vipText: { fontSize: 12.5, fontWeight: "900", color: COLORS.TEXT },

    statsRow: { flexDirection: "row", gap: 12, marginTop: 12 },
    statCard: {
        flex: 1,
        backgroundColor: COLORS.CARD,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: COLORS.BORDER,
        paddingVertical: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    statIcon: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", marginBottom: 8 },
    statValue: { fontSize: 18, fontWeight: "900", color: COLORS.TEXT },
    statLabel: { marginTop: 4, fontSize: 12, fontWeight: "700", color: COLORS.SUB },

    group: {
        marginTop: 12,
        backgroundColor: COLORS.CARD,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: COLORS.BORDER,
        overflow: "hidden",
    },
    row: {
        height: 64,
        paddingHorizontal: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        borderTopWidth: 1,
        borderTopColor: COLORS.BORDER,
        backgroundColor: COLORS.CARD,
    },
    rowLast: {},
    rowLeft: { flexDirection: "row", alignItems: "center", gap: 12, flex: 1, paddingRight: 10 },
    rowIcon: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" },
    rowTitle: { fontSize: 14, fontWeight: "900", color: COLORS.TEXT },
    rowSub: { marginTop: 4, fontSize: 12, fontWeight: "700", color: COLORS.MUTED },
    rowRight: { flexDirection: "row", alignItems: "center", gap: 10 },
    rowBadge: {
        minWidth: 22,
        height: 20,
        borderRadius: 10,
        backgroundColor: COLORS.RED,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 6,
    },
    rowBadgeText: { color: COLORS.WHITE, fontSize: 11, fontWeight: "900" },

    logoutBtn: {
        marginTop: 12,
        height: 54,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: COLORS.BORDER,
        backgroundColor: COLORS.WHITE,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
    },
    logoutText: { fontSize: 14, fontWeight: "900", color: COLORS.RED },
});

export default styles;
