import { StyleSheet } from "react-native";

export const COLORS = {
    BG: "#F6F8FC",
    TEXT: "#111",
    SUB: "#6B7280",
    BLUE: "#0B63F6",
    BORDER: "#EEF2F8",
    CARD: "#fff",
    GREEN: "#22C55E",
    RED: "#EF4444",

    GRAY_BG: "#EFEFEF",
    MUTED: "#9AA0A6",
    IMG_BG: "#F2F2F2",
    LIGHT_BLUE_BORDER: "#D6E6FF",
};

const styles = StyleSheet.create({
    safe: { flex: 1, backgroundColor: COLORS.BG },

    header: {
        paddingHorizontal: 12,
        paddingTop: 6,
        paddingBottom: 8,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    headerBtn: { width: 40, height: 40, borderRadius: 12, alignItems: "center", justifyContent: "center" },
    headerTitle: { flex: 1, fontSize: 18, fontWeight: "900", color: COLORS.TEXT },

    searchWrap: {
        flex: 1,
        height: 40,
        borderRadius: 12,
        backgroundColor: COLORS.GRAY_BG,
        paddingHorizontal: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    searchInput: { flex: 1, fontSize: 13.5, fontWeight: "700", color: COLORS.TEXT },

    tabs: { paddingHorizontal: 12, gap: 18, paddingBottom: 6 },
    tab: { paddingVertical: 6 },
    tabRow: { flexDirection: "row", alignItems: "center", gap: 8 },
    tabText: { fontSize: 13, fontWeight: "900", color: COLORS.MUTED },
    tabTextActive: { color: COLORS.BLUE },
    tabCount: {
        height: 18,
        minWidth: 22,
        borderRadius: 9,
        backgroundColor: "#E5E7EB",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 6,
    },
    tabCountActive: { backgroundColor: COLORS.LIGHT_BLUE_BORDER },
    tabCountText: { fontSize: 11, fontWeight: "900", color: COLORS.SUB },
    tabCountTextActive: { color: COLORS.BLUE },
    tabUnderline: { marginTop: 8, height: 2, backgroundColor: COLORS.BLUE, borderRadius: 1 },
    tabsList: { flexGrow: 0 },
    summaryRow: {
        paddingHorizontal: 12,
        paddingTop: 8,
        paddingBottom: 6,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    summaryText: { fontSize: 12.5, fontWeight: "800", color: COLORS.SUB },
    smallFilterBtn: {
        height: 34,
        paddingHorizontal: 10,
        borderRadius: 10,
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: COLORS.LIGHT_BLUE_BORDER,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    smallFilterText: { fontSize: 12.5, fontWeight: "900", color: COLORS.BLUE },

    loadingWrap: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10 },
    loadingText: { fontSize: 13, fontWeight: "800", color: COLORS.SUB },

    list: { paddingHorizontal: 12, paddingTop: 10, paddingBottom: 18, gap: 12 },

    empty: {
        marginTop: 18,
        backgroundColor: "#fff",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: COLORS.BORDER,
        padding: 18,
        alignItems: "center",
        gap: 6,
    },
    emptyTitle: { marginTop: 6, fontSize: 14, fontWeight: "900", color: COLORS.TEXT },
    emptySub: { fontSize: 12, fontWeight: "700", color: COLORS.MUTED },

    card: { backgroundColor: COLORS.CARD, borderRadius: 16, borderWidth: 1, borderColor: COLORS.BORDER, padding: 12 },

    cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
    code: { fontSize: 14, fontWeight: "900", color: COLORS.TEXT },
    dateRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 6 },
    dateText: { fontSize: 12, fontWeight: "700", color: COLORS.MUTED },

    payRowMini: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 6 },
    payTextMini: { fontSize: 12, fontWeight: "800", color: COLORS.MUTED },

    statusPill: { borderRadius: 14, paddingHorizontal: 10, height: 28, alignItems: "center", justifyContent: "center" },
    statusText: { fontSize: 12, fontWeight: "900" },

    thumbRow: { flexDirection: "row", gap: 10, marginTop: 10 },
    thumbBox: {
        width: 54,
        height: 54,
        borderRadius: 12,
        backgroundColor: COLORS.IMG_BG,
        overflow: "hidden",
        borderWidth: 1,
        borderColor: COLORS.BORDER,
    },
    thumbImg: { width: "100%", height: "100%", resizeMode: "cover" },

    midRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 10 },
    itemsText: { fontSize: 12.5, fontWeight: "800", color: COLORS.SUB },
    total: { fontSize: 16, fontWeight: "900", color: COLORS.BLUE },

    actions: { flexDirection: "row", gap: 12, marginTop: 12 },
    btn: {
        flex: 1,
        height: 42,
        borderRadius: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        borderWidth: 1,
    },
    btnText: { fontSize: 13, fontWeight: "900" },
    btnOutline: { backgroundColor: "#fff", borderColor: COLORS.LIGHT_BLUE_BORDER },
    btnOutlineBlue: { backgroundColor: "#fff", borderColor: COLORS.BLUE },

    fab: {
        position: "absolute",
        right: 18,
        bottom: 18,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: COLORS.BLUE,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOpacity: 0.18,
        shadowRadius: 10,
        elevation: 5,
    },

    modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.35)", justifyContent: "flex-end" },
    sheet: {
        backgroundColor: "#fff",
        borderTopLeftRadius: 18,
        borderTopRightRadius: 18,
        borderWidth: 1,
        borderColor: COLORS.BORDER,
        overflow: "hidden",
        maxHeight: "86%",
    },
    sheetHeader: {
        height: 54,
        paddingHorizontal: 14,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.BORDER,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    sheetTitle: { fontSize: 16, fontWeight: "900", color: COLORS.TEXT },
    sheetClose: { width: 40, height: 40, borderRadius: 12, alignItems: "center", justifyContent: "center" },

    sheetBody: { paddingHorizontal: 14, paddingTop: 12, paddingBottom: 12 },
    fTitle: { fontSize: 13, fontWeight: "900", color: COLORS.TEXT, marginBottom: 10 },

    fChipRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
    fChip: {
        height: 34,
        paddingHorizontal: 12,
        borderRadius: 17,
        backgroundColor: "#F3F4F6",
        borderWidth: 1,
        borderColor: "#E5E7EB",
        alignItems: "center",
        justifyContent: "center",
    },
    fChipOn: { backgroundColor: "#EAF2FF", borderColor: COLORS.LIGHT_BLUE_BORDER },
    fChipText: { fontSize: 12.5, fontWeight: "900", color: COLORS.SUB },
    fChipTextOn: { color: COLORS.BLUE },

    amountRow: { flexDirection: "row", gap: 10 },
    amountBox: {
        flex: 1,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: "#E5E7EB",
        backgroundColor: "#FBFBFB",
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    amountLabel: { fontSize: 12, fontWeight: "900", color: COLORS.SUB, marginBottom: 6 },
    amountInput: { fontSize: 14, fontWeight: "900", color: COLORS.TEXT },

    fSortBox: { backgroundColor: "#fff", borderRadius: 14, borderWidth: 1, borderColor: COLORS.BORDER, overflow: "hidden" },
    fRowBtn: {
        height: 48,
        paddingHorizontal: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        borderTopWidth: 1,
        borderTopColor: COLORS.BORDER,
    },
    fRowBtnOn: { backgroundColor: "#F7FAFF" },
    fRowBtnText: { fontSize: 13.5, fontWeight: "900", color: COLORS.TEXT },
    fRowBtnTextOn: { color: COLORS.BLUE },

    sheetFooter: {
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: COLORS.BORDER,
        flexDirection: "row",
        gap: 12,
    },
    footerBtn: { flex: 1, height: 46, borderRadius: 14, alignItems: "center", justifyContent: "center" },
    footerPrimary: { backgroundColor: COLORS.BLUE },
    footerGhost: { backgroundColor: "#fff", borderWidth: 1, borderColor: COLORS.LIGHT_BLUE_BORDER },
    footerBtnText: { fontSize: 14, fontWeight: "900" },
});

export default styles;
